# Generated by Django 3.0.3 on 2020-02-18 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('toppings_no', models.IntegerField(blank=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_cat', to='ordering_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NP', 'Not Placed'), ('PL', 'Placed'), ('IN', 'In Progress'), ('CO', 'Completed')], max_length=2)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('O', 'One Size'), ('S', 'Small'), ('L', 'Large')], max_length=1)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_cat', to='ordering_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_food_id', to='ordering_app.Food')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_food_id', to='ordering_app.Food')),
                ('food_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_price_id', to='ordering_app.Price')),
                ('food_topping1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_topping1_id', to='ordering_app.Topping')),
                ('food_topping2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_topping2_id', to='ordering_app.Topping')),
                ('food_topping3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_topping3_id', to='ordering_app.Topping')),
                ('food_topping4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_topping4_id', to='ordering_app.Topping')),
                ('food_topping5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_topping5_id', to='ordering_app.Topping')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='ordering_app.Order')),
            ],
        ),
    ]
