# Generated by Django 3.0.3 on 2020-02-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='toppings_no',
            field=models.IntegerField(default=0),
        ),
    ]
