# Generated by Django 3.0.3 on 2020-02-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_app', '0005_auto_20200221_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(height_field=250, null=True, upload_to='food', width_field=250),
        ),
    ]
