# Generated by Django 3.0.3 on 2020-03-10 12:23

from django.db import migrations, models
import ordering_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_app', '0007_auto_20200221_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(null=True, upload_to=ordering_app.models.save_img),
        ),
    ]
